#!/bin/sh
if [ -z ${IP+x} ]; then
IP=$(/sbin/ip route|awk '/tun0/ { print $1 }' |grep -v /24)
echo "eth0 ip is $IP"
fi
if [ -z ${HOSTNAME+x} ]; then
  HOSTNAME=$(cat /etc/hostname)
fi
if [ -z ${IP+x} ]; then echo "IP is unset"; else
  pdd_delete $TOKEN $DOMAIN $HOSTNAME
  if [ -z ${DELETE_ONLY+x} ]; then
    pdd_create  $TOKEN $DOMAIN "$HOSTNAME&A&$IP"
  fi
fi
